### ISSUE TITLE
Getting it working with latest Node and Python versions

### ISSUE THREAD

**Issue by Smilebags** [fresc81/logiled#2]
Hi, great little package here, I've used it a couple of times and it has been very helpful.

The most up to date version I've been able to run it on is Node 8.16. I've recently updated my machine and am running Python 3.7 and Node 12/13 usually.

I've mostly run into issues with Python's syntax changing and some 'version probe' failed to run, as well as the following error when attempting to compile, due to MSBuild being in `Current/Bin/MSBuild.exe` instead of `15.0`.
`Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT`

I'm just inquiring to see how much effort you think it would be to get this running with up-to-date versions of dependencies? I'm hoping that my lack of knowledge in to C/C++/Python development is the main cause of my issues here, and not a more fundamental problem.

Happy to contribute what I can to get this up and running, I think it can be a useful tool for years to come.

**Comment by fresc81** [comment]
Hi, thanks for your report. I updated the dependencies which fixed the security issues. The errors with the environment variables went away, when I set up the build commands to be run by npx.
It compiles with Visual Studio 2019 now. The code that downloads the Logitech LED SDK could need some love. But I also got prebuild working again so this shouldn't be a big issue.

**Comment by Smilebags** [comment]
Hi, thanks for your latest work on this, it's working perfectly again!
